repos:

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python
    exclude: ^modelmaker/resources/

- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
